services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: massimo-v2:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
